version: 2

jobs:
  build:
    docker:
      - image: circleci/android:api-26-alpha
    steps:
      - checkout
      - run:
          name: wat
          command: bundle install
          environment:
            BUNDLE_JOBS: 3
            BUNDLE_RETRY: 3
            BUNDLE_PATH: vendor/bundle
      - run:
          command: PATH=~/.bundle/bin:$PATH bundle exec fastlane test
          name: try this
      
