version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Hello World
          command: ulimit -n
      - run:
          name: Generate Files
          command: |
            mkdir build
            for n in {0001..5000}; do
              cp main.py build/main-copy-$n.jpg
            done
      - store_artifacts:
          path: build

