version: 2
workflows:
  version: 2
  regular_workflow:
    jobs:
      - 'build1'
      - 'build2'
      - 'build3'
      - 'build4'
      - 'build5'
      - 'build6'
      - 'build7'
      - 'build8'
      - 'build9'
      - 'build10'
      - 'build11'
      - 'build12'
      - 'build13'
      - 'build14'
      - 'build15'
      - 'build16'
      - 'build17'
      - 'build18'
      - 'build19'
      - 'build20'
      - 'build21'
      - 'build22'
      - 'build23'
      - 'build24'

jobs:
  build1:
    macos:
      xcode: 10.1.0
    resource_class: 'large'
    steps:
      - checkout
  build2:
    macos:
      xcode: 10.1.0
    resource_class: 'large'
    steps:
      - checkout
  build3:
    macos:
      xcode: 10.1.0
    resource_class: 'large'
    steps:
      - checkout
  build4:
    macos:
      xcode: 10.1.0
    resource_class: 'large'
    steps:
      - checkout
  build5:
    macos:
      xcode: 10.1.0
    resource_class: 'large'
    steps:
      - checkout
  build6:
    macos:
      xcode: 10.1.0
    resource_class: 'large'
    steps:
      - checkout
  build7:
    macos:
      xcode: 10.1.0
    resource_class: 'large'
    steps:
      - checkout
  build8:
    macos:
      xcode: 10.1.0
    resource_class: 'large'
    steps:
      - checkout
  build9:
    macos:
      xcode: 10.1.0
    resource_class: 'large'
    steps:
      - checkout
  build10:
    macos:
      xcode: 10.1.0
    resource_class: 'large'
    steps:
      - checkout
  build11:
    macos:
      xcode: 10.1.0
    resource_class: 'large'
    steps:
      - checkout
  build12:
    macos:
      xcode: 10.1.0
    resource_class: 'large'
    steps:
      - checkout
  build13:
    macos:
      xcode: 10.1.0
    resource_class: 'large'
    steps:
      - checkout
  build14:
    macos:
      xcode: 10.1.0
    resource_class: 'large'
    steps:
      - checkout
  build15:
    macos:
      xcode: 10.1.0
    resource_class: 'large'
    steps:
      - checkout
  build16:
    macos:
      xcode: 10.1.0
    resource_class: 'large'
    steps:
      - checkout
  build17:
    macos:
      xcode: 10.1.0
    resource_class: 'large'
    steps:
      - checkout
  build18:
    macos:
      xcode: 10.1.0
    resource_class: 'large'
    steps:
      - checkout
  build19:
    macos:
      xcode: 10.1.0
    resource_class: 'large'
    steps:
      - checkout
  build20:
    macos:
      xcode: 10.1.0
    resource_class: 'large'
    steps:
      - checkout
  build21:
    macos:
      xcode: 10.1.0
    resource_class: 'large'
    steps:
      - checkout
  build22:
    macos:
      xcode: 10.1.0
    resource_class: 'large'
    steps:
      - checkout
  build23:
    macos:
      xcode: 10.1.0
    resource_class: 'large'
    steps:
      - checkout
  build24:
    macos:
      xcode: 10.1.0
    resource_class: 'large'
    steps:
      - checkout
