version: 2
jobs:
  build:
    working_directory: /Users/marc/dev/repo
    docker:
      - image: gcc:7
    steps:
      - checkout
      - run:
          name: Hello World
          command: echo Hello World
