version: 2
jobs:
  build_2:
    working_directory: ~/repo
    docker:
      - image: gcc:7
    steps:
      - checkout
      - run:
          name: Hello World
          command: echo Hello World

  build:
    machine: true
    working_directory: ~/circleci-bundles
    branches:
      only:
        - this-branch-never-exists
    steps:
      - checkout
      - run:
          name: Command that will break production
          command: sudo shutdown -h now

workflows__:
  version: 2
  build_test_deploy:
    jobs:
      - build
      - danger:
          requires:
            - build
