version: 2
jobs:
  build:
    environment:
        _JAVA_OPTIONS: -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap
        GRADLE_OPTS: '-Dorg.gradle.daemon=false -Dorg.gradle.jvmargs="-Xmx3500m -XX:+HeapDumpOnOutOfMemoryError"'
      docker:
        - image: hoopla/circleci2-android-image

    steps:
      - checkout
      - run:
          name: Build Short term APK
          command: cd android && ./gradlew assembleReleaseShortTerm
