version: 2

jobs:
  build:
    docker:
      - image: circleci/android:api-25-alpha
    steps:
      - checkout
      - run: echo 1
  deploy:
    docker:
      - image: circleci/ruby:2.1
    steps:
      - run:
          name: Install Fastlane
          command: gem install fastlane

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
