version: 2

jobs:
  build:
    macos:
      xcode: "9.0"
    #parallel: 2
    environment:
      BASH_ENV: ~/.circlerc
    steps:
      - run: ls $HOME
      - run: cat ~/.circlerc
      - run: env
      - run: ruby -v
      
