version: 2

jobs:
  build:
    macos:
      xcode: "9.0"
    #parallel: 2
    environment:
      BASH_ENV: /Users/distiller/.circlerc
    steps:
      - run: ls $HOME
      - run: source $BASH_ENV && cat ~/.circlerc
      - run: env
      - run: source $BASH_ENV && cat ~/.circlerc && ruby -v
      
