# A config with no workflow defined.
# Just a single job.
version: 2
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:18.04-curl
    steps:
      - checkout
workflows:
  version: 2
  commit:
    jobs:
      - build
  frequent:
    triggers:
      - schedule:
          cron: "*/5 * * * *"
          filters:
            branches:
              only:
                - master
                - beta
    jobs:
      - build
