version: 2

jobs:
  build:
    docker:
      - image: circleci/android:api-26-alpha
    steps:
      - checkout
      - run:
          name: wat
          command: bundle install --path vendor/bundle
          environment:
            BUNDLE_JOBS: 3
            BUNDLE_RETRY: 3
      - run:
          command: bundle exec fastlane test
          name: try this
      
