
# A config with no workflow defined.
# Just a single job.

version: 2
jobs:
  build:
    docker:
      - image: buildpack-deps:16.04-curl
    steps:
      - run: env
      - run: sleep 30
      - run: sleep 30
      - run: sleep 30
      - run: sleep 30
      - run: sleep 30
      - run: sleep 30
      - run: sleep 30
      - run: sleep 30
      - run: sleep 30
      - run: sleep 30
      - run: sleep 30
      - run: sleep 30
      - run: sleep 30
      - run: sleep 30
      - run: sleep 30
      - run: sleep 30
      - run: sleep 30
      - run: sleep 30
      - run: sleep 30
      - run: sleep 30
      - run: sleep 30
