version: 2

jobs:
  build:
    environment:
      BASH_ENV: $HOME/.bashrc
    macos:
      xcode: "9.0"
    steps:
      - checkout
      - run: cat ~/.bashrc
      - run: cat ~/.bash_profile

      - run: echo 'echo loaded bash_profile' >> ~/.bash_profile
      - run: echo 'echo loaded bashrc' >> ~/.bashrc
      - run: echo $BASH_ENV
      - run: ruby -v
      - run: launchctl setenv BASH_ENV $HOME/.bash_profile
      - run: echo $BASH_ENV
      - run: ruby -v
      
