version: 2
jobs:
  build:
    docker:
      - image: druffer/gforth:latest
    steps:
      - run:
          name: Phil Made Me Do This
          shell: /usr/bin/env gforth
          command: |
            2 3 + . 
            bye