version: 2
jobs:
  config_processing_exception:
    steps:
      - run:
          name: Unexpected exception processing config - Please contact support
          command: "false"
    docker: [image: 'debian:stretch']
workflows:
  version: 2
  config_processing_exception: {jobs: [config_processing_exception]}
